# Generated by Django 5.1.1 on 2024-09-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('probability', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('s_weight', models.FloatField(blank=True, null=True)),
                ('a_weight', models.FloatField(blank=True, null=True)),
                ('b_weight', models.FloatField(blank=True, null=True)),
                ('c_weight', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(default=1.75)),
                ('standard_deviation', models.FloatField(default=0.625)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FishCatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('rarity_level', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fish_catched', models.ManyToManyField(to='app.fishcatched')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
